# -*- coding: utf-8 -*-
"""Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P8dCRrlblbYUGGFRNBF5eKky3rG7A0y-
"""

print('Hellow, World!')

if 5>2:
  print('Five is graeter than two')

if 5>2:
  print('Five is graeter than two')
if 5>2:
          print('Five is graeter than two')

x=5
y='Ashik'
#x= 5 int type variable
#y= 'Ashik' str type variable
print(x)
print(y)

x,y,z='Ashik','Sinthi','Aiza'
print(x)
print(y)
print(z)

x=y=z='Ashik'
print(x)
print(y)
print(z)

fruits=['Ashik','Sinthi','Aiza']
x,y,z=fruits
print(x)
print(y)
print(z)

x='I am Ashik'
print(x)
x='I'
y='am'
z='Ashik'
print(x,y,z)
x='I '
y='am '
z='Ashik'
print(x+y+z)

x='Ashik'
def myfunc():
  print('I am ' +x)
myfunc()

x=str('3')
y=int(3)
z=float(3)
print(x)
print(y)
print(z)
print(type(x))

x,y,z=['Orange','Apple','Banana']
print(x)
print(y)
print(z)

x='awesome'
def myfunc():
  print('Python is '+ x)
myfunc()

x='awesome'
def myfunc():
  x='fantastic'
  print('Python is '+ x)
myfunc()
print('Python is '+ x)

import random
print(random.randrange(1,21))

x=5
y=10.05
z=1j

a=float(x)
b=int(y)
c=complex(y)

print(a)
print(b)
print(c)

print(type(a))
print(type(b))
print(type(c))

today=date.today()
if today==date (2025,8,28):
  print("Happy Birthday")
else:
  print("It is a normal day")

today=date.today()
deadline=date(2025,8,26)
if today<deadline:
  print("You are before the deadline")
else:
  print("The deadline has passed.")

a='Ashik'
print(a[2])

for x in 'Ashik':
 print(x)

a='Ashik'
print(len(a))

a='I am an Engineer'
if 'Engineer' in a:
  print('This sentence is correct')

a='I am an Engineer'
print('Engineer' in a)

a= 'Ashik'
print(a.upper())

for x in "Ashik":
 print(x)

x="The best things in life are free"
if "free" in x:
 print(x)

x="The best things in life are free!"
print("free" in x)

x="The best things in life are free"
if "free" in x:
 print('Yes,"free" is present')

x='The best things in life are free'
print("free" not in x)

x="The best things in life are free"
print('free' not in x)

txt = "The best things in life are free!"
if "expensive" not in txt:
  print("No, 'expensive' is NOT present.")

x='Ashik'
print(x[2:4])

x='Ashik'
print(x.upper())

x='Ashik'
print(x.lower())

a = " Hello, World! "
print(a.strip())

x=" Ashik is the best "
print(x.strip())

a= "Japan Garden"
print(a.replace('Japan', 'India'))

numbers = {5, 2, 9, 1}
print(numbers)

thislist = ["apple", "banana", "cherry"]
thislist[1]='orange'
print(thislist)

thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]
thislist[1:3]=['Ashik','Aiza']
print(thislist)

fruits = ["apple", "banana", "cherry",'mango']
newlist=[]
for x in fruits:
  if 'a' in x:
   newlist.append(x)
print(newlist)

fruits = ["apple", "banana", "cherry", "mango"]

newlist = [x for x in fruits if "a" in x]

print(newlist)

fruits = ["apple", "banana", "cherry", "mango"]
newlist=[x for x in fruits if 'apple'== x]
print(newlist)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist=[x.lower()for x in fruits]
print(newlist)

def myfunc(n):
  return abs(n - 50)

thislist = [100, 50, 65, 82, 23]
thislist.sort(key = myfunc)
print(thislist)

numbers = {5, 2, 9, 1}
print(numbers)

thisdict={
    "Brand" : "Ashik",
    "Model" : "Aiza",
    "Date" : 1970
}
print(thisdict)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist=[x if x !="banana" else "orange" for x in fruits]
print(newlist)

thisdict={
    "Brand": "Ashik",
    "Name" : "Aiza",
    "Date" : 1975
}
print(thisdict["Brand"])

thisdict= dict(brand='Ashik',Name= 'Aiza, Age : 36')
print(thisdict)

thisdict={
    "Name":"Ashik",
    "Model": "Aiza",
    "Age": 2
}
x=thisdict["Model"]
print(x)

thisdict={
    "Name":"Ashik",
    "Model": "Aiza",
    "Age": 2
}
x=thisdict.get("Model")
print(x)

thisdict={
    "Name":"Ashik",
    "Model": "Aiza",
    "Age": 2
}
thisdict["Age"]=35
print(thisdict)

thisdict={
    "Name":"Ashik",
    "Model": "Aiza",
    "Age": 2
}
thisdict.update({"Age": 40})
print(thisdict)

myfamily={
    "Member1":{
        "Name":"Foyes Ahmed",
        "Address":"Rampura, Dhaka",
        "Age":36
    },
    "Member02":{
        "Name":"Md. Ashikur Rahman",
        "Address":"Mohammadpur, Dhaka",
        "Age":33
    },
    "Member03":{
        "Name":"Md. Azizur Rahman",
        "Address":"Chapai Nawabganj",
        "Age":66
    },
}
print(myfamily)

my_list = [-1,0,1]
my_array = np.array(my_list)
my_array
my_array[0]